# Generated by Django 3.2.6 on 2021-08-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255, null=True)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'CUSTOMER_MASTER',
            },
        ),
    ]
